#!/bin/bash

filename="_posts/$(TZ=Asia/Tokyo date +%Y-%m-%d-%H%M%S%5N)${RANDOM}.markdown"

cat > ${filename} <<PTEMPLATE
---
layout: post
date: $(TZ=Asia/Tokyo date "+%F %H:%M")
---

PTEMPLATE

ruby _lib/${1} >> ${filename}
