#!/bin/bash

filename="_posts/$(TZ=-9 date +%Y-%m-%d-%H%M%S%5N)${RANDOM}.markdown"

cat > ${filename} <<PTEMPLATE
---
layout: post
date: $(TZ=-9 date "+%F %H:%M")
---

PTEMPLATE

ruby _lib/${1} >> ${filename}
