#!/bin/bash

title=$(date '+%F%T' | md5sum | awk '{print $1}')
filename="_posts/`date +%Y-%m-%d-"${title}".markdown`"
filename=${filename//" "/"_"}

cat > $filename <<PTEMPLATE
---
layout: post
date: $(date "+%F %H:%M")
---

PTEMPLATE

ruby _lib/${1} >> $filename
