---
# This workflow runs a scheduled job to generate and commit posts using Ruby.
# It uses third-party actions that are not certified by GitHub.
# For more details, see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: clean

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write  # Required for committing changes

jobs:
  generate_posts:
    name: Generate and Commit Posts
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        ruby: [3]  # Specify the desired Ruby version

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Generate and Commit Posts
        run: |
          [ "$(ls _posts | wc -l)" -gt 9 ] && ls _posts | sort | head -n -9 | xargs rm -f
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add _posts/*
          git commit -m "Auto commit: $(date)" || echo "No changes to commit"
          git push origin HEAD
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
